=== EstiZozaya/pbl_grupo_5/WEB/PBL_Talde5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Analisis_Software">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Paciente" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Sexo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Hombre"/>
                                        <xs:enumeration value="Mujer"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Hospital" type="xs:string"/>
                            <xs:element name="Telefono">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[67]\d{8}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="HistorialMedico">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Entrada" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Fecha">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="\d{4}-\d{2}-\d{2}"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="Descripcion" type="xs:string"/>
                                                    <xs:element name="Tratamiento">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:choice maxOccurs="unbounded">
                                                                    <xs:element name="Medicacion">
                                                                        <xs:complexType>
                                                                            <xs:sequence>
                                                                                <xs:element name="NombreMed" type="xs:string"/>
                                                                                <xs:element name="Dosis">
                                                                                    <xs:simpleType>
                                                                                        <xs:restriction base="xs:string">
                                                                                            <xs:pattern value="\d+(mg|g)"/>
                                                                                        </xs:restriction>
                                                                                    </xs:simpleType>
                                                                                </xs:element>
                                                                                <xs:element name="Frecuencia" type="xs:string"/>
                                                                            </xs:sequence>
                                                                        </xs:complexType>
                                                                    </xs:element>
                                                                    <xs:element name="Procedimiento">
                                                                        <xs:complexType>
                                                                            <xs:sequence>
                                                                                <xs:element name="Tipo" type="xs:string"/>
                                                                            </xs:sequence>
                                                                        </xs:complexType>
                                                                    </xs:element>
                                                                </xs:choice>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Glaucoma">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Diagnostico">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Resultado">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="Si"/>
                                                                <xs:enumeration value="No"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="FechaDiagnostico">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="\d{4}-\d{2}-\d{2}"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
													<xs:element name="Imagen"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="\d{4}[A-Z]{3}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== EstiZozaya/pbl_grupo_5/WEB/PBL_Talde5.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="PBL_Talde5.xslt"?>
<Analisis_Software xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PBL_Talde5.xsd">
	<Paciente id="7834RTG">
		<Sexo>Hombre</Sexo>
		<Hospital>Alto Deba</Hospital>
		<Telefono>648947623</Telefono>
		<HistorialMedico>
            <Entrada>
                <Fecha>2010-05-20</Fecha>
                <Descripcion>Diagnóstico de Diabetes Tipo 2</Descripcion>
                <Tratamiento>
                    <Medicacion>
                        <NombreMed>Metformina</NombreMed>
                        <Dosis>500mg</Dosis>
                        <Frecuencia>2 veces al día</Frecuencia>
                    </Medicacion>
                </Tratamiento>
            </Entrada>
            <Entrada>
                <Fecha>2015-08-15</Fecha>
                <Descripcion>Cirugía de Cataratas</Descripcion>
                <Tratamiento>
                    <Procedimiento>
                        <Tipo>Extracción de Cataratas</Tipo>
                    </Procedimiento>
                </Tratamiento>
            </Entrada>
		</HistorialMedico>
		<Glaucoma>
			<Diagnostico>
				<Resultado>Si</Resultado>
				<FechaDiagnostico>2022-11-15</FechaDiagnostico>
				<Imagen>C:\Users\izaro\OneDrive\Escritorio\biomedika\TERCERO\Segundo cuatri\PBL\MIO\WEB\ImagenesPBL\Glaucoma.jpg</Imagen>
			</Diagnostico>
		</Glaucoma>
	</Paciente>
	<Paciente id="6729LMT">
		<Sexo>Mujer</Sexo>
		<Hospital>Hospital de Navarra</Hospital>
		<Telefono>787250293</Telefono>
		<HistorialMedico>
            <Entrada>
                <Fecha>2014-07-18</Fecha>
                <Descripcion>Diagnóstico de Cancer de Pancreas</Descripcion>
                <Tratamiento>
                    <Medicacion>
                        <NombreMed>Eribulina</NombreMed>
                        <Dosis>500mg</Dosis>
                        <Frecuencia>1 al día</Frecuencia>
                    </Medicacion>
                </Tratamiento>
            </Entrada>
		</HistorialMedico>
		<Glaucoma>
			<Diagnostico>
				<Resultado>No</Resultado>
				<FechaDiagnostico>2022-11-15</FechaDiagnostico>
				<Imagen>C:\Users\izaro\OneDrive\Escritorio\biomedika\TERCERO\Segundo cuatri\PBL\MIO\WEB\ImagenesPBL\Glaucoma2.jpg</Imagen>
			</Diagnostico>
		</Glaucoma>
	</Paciente>
</Analisis_Software>

=== EstiZozaya/pbl_grupo_5/docs/PBL_Talde5.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="PBL_Talde5.xslt"?>
<Analisis_Software xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PBL_Talde5.xsd">
	<Paciente id="7834RTG">
		<Sexo>Hombre</Sexo>
		<Hospital>Alto Deba</Hospital>
		<Telefono>648947623</Telefono>
		<HistorialMedico>
            <Entrada>
                <Fecha>2010-05-20</Fecha>
                <Descripcion>Diagnóstico de Diabetes Tipo 2</Descripcion>
                <Tratamiento>
                    <Medicacion>
                        <NombreMed>Metformina</NombreMed>
                        <Dosis>500mg</Dosis>
                        <Frecuencia>2 veces al día</Frecuencia>
                    </Medicacion>
                </Tratamiento>
            </Entrada>
            <Entrada>
                <Fecha>2015-08-15</Fecha>
                <Descripcion>Cirugía de Cataratas</Descripcion>
                <Tratamiento>
                    <Procedimiento>
                        <Tipo>Extracción de Cataratas</Tipo>
                    </Procedimiento>
                </Tratamiento>
            </Entrada>
		</HistorialMedico>
		<Glaucoma>
			<Diagnostico>
				<Resultado>Si</Resultado>
				<FechaDiagnostico>2022-11-15</FechaDiagnostico>
				<Imagen>ImagenesPBL/Glaucoma.jpg</Imagen>
			</Diagnostico>
		</Glaucoma>
	</Paciente>
	<Paciente id="6729LMT">
		<Sexo>Mujer</Sexo>
		<Hospital>Hospital de Navarra</Hospital>
		<Telefono>787250293</Telefono>
		<HistorialMedico>
            <Entrada>
                <Fecha>2014-07-18</Fecha>
                <Descripcion>Diagnóstico de Cancer de Pancreas</Descripcion>
                <Tratamiento>
                    <Medicacion>
                        <NombreMed>Eribulina</NombreMed>
                        <Dosis>500mg</Dosis>
                        <Frecuencia>1 al día</Frecuencia>
                    </Medicacion>
                </Tratamiento>
            </Entrada>
		</HistorialMedico>
		<Glaucoma>
			<Diagnostico>
				<Resultado>No</Resultado>
				<FechaDiagnostico>2022-11-15</FechaDiagnostico>
				<Imagen>ImagenesPBL/Glaucoma2.jpg</Imagen>
			</Diagnostico>
		</Glaucoma>
	</Paciente>
	<Paciente id="4962GTV">
		<Sexo>Mujer</Sexo>
		<Hospital>Txagorritxu</Hospital>
		<Telefono>649186227</Telefono>
		<HistorialMedico>
            <Entrada>
                <Fecha>2008-11-05</Fecha>
                <Descripcion>Hipertensión</Descripcion>
                <Tratamiento>
                    <Medicacion>
                        <NombreMed>Enalparil</NombreMed>
                        <Dosis>5mg</Dosis>
                        <Frecuencia>1 vez al día</Frecuencia>
                    </Medicacion>
                </Tratamiento>
            </Entrada>
            <Entrada>
                <Fecha>2012-01-02</Fecha>
                <Descripcion>Extirpación de lipoma</Descripcion>
                <Tratamiento>
                    <Procedimiento>
                        <Tipo>Extracción de un lipoma</Tipo>
                    </Procedimiento>
                </Tratamiento>
            </Entrada>
		</HistorialMedico>
		<Glaucoma>
			<Diagnostico>
				<Resultado>Si</Resultado>
				<FechaDiagnostico>2023-05-24</FechaDiagnostico>
				<Imagen>ImagenesPBL/Glaucoma4.jpg</Imagen>
			</Diagnostico>
		</Glaucoma>
	</Paciente>
	<Paciente id="8195MKR">
		<Sexo>Hombre</Sexo>
		<Hospital>Cruces</Hospital>
		<Telefono>618925486</Telefono>
		<HistorialMedico>
            <Entrada>
                <Fecha>1999-02-14</Fecha>
                <Descripcion>Asma</Descripcion>
                <Tratamiento>
                    <Medicacion>
                        <NombreMed>Fluticasona</NombreMed>
                        <Dosis>250mcg</Dosis>
                        <Frecuencia>Inhalación 2 veces al día</Frecuencia>
                    </Medicacion>
                </Tratamiento>
            </Entrada>
		</HistorialMedico>
		<Glaucoma>
			<Diagnostico>
				<Resultado>No</Resultado>
				<FechaDiagnostico>2024-06-04</FechaDiagnostico>
				<Imagen>ImagenesPBL/Glaucoma3.jpg</Imagen>
			</Diagnostico>
		</Glaucoma>
	</Paciente>
	<Paciente id="2189JVR">
		<Sexo>Hombre</Sexo>
		<Hospital>Alto Deba</Hospital>
		<Telefono>614962846</Telefono>
		<HistorialMedico>
            <Entrada>
                <Fecha>2000-04-19</Fecha>
                <Descripcion>Hipotiroidismo</Descripcion>
                <Tratamiento>
                    <Medicacion>
                        <NombreMed>Levotiroxina</NombreMed>
                        <Dosis>50 mcg</Dosis>
                        <Frecuencia>Una vez al día</Frecuencia>
                    </Medicacion>
                </Tratamiento>
            </Entrada>
		</HistorialMedico>
		<Glaucoma>
			<Diagnostico>
				<Resultado>Si</Resultado>
				<FechaDiagnostico>2023-06-01</FechaDiagnostico>
				<Imagen>ImagenesPBL/Glaucoma5.jpg</Imagen>
			</Diagnostico>
		</Glaucoma>
	</Paciente>
</Analisis_Software>
